### ISSUE TITLE
Dead readme links: storage provider support

### ISSUE THREAD

**Issue by jzaefferer** [thecodeteam/rexray#1079]
This section in the readme has lots of dead links: https://github.com/codedellemc/rexray#storage-provider-support

Like this: https://github.com/codedellemc/rexray/blob/master/user-guide/storage-providers.md#aws-ebs

Should go to https://github.com/codedellemc/rexray/blob/master/.docs/user-guide/storage-providers/aws.md instead? 

Or http://rexray.readthedocs.io/en/stable/user-guide/storage-providers/aws/ ?

**Comment by clintkitson** [comment]
Hello @jzaefferer,

I believe this is a caching problem. Can you try a forced refresh of the main page? Cmd->Shift->R?

**Comment by jzaefferer** [comment]
This isn't a caching problem.

**Comment by clintkitson** [comment]
Thank you @jzaefferer, I dealt with something similar and figured it was in the RTFD docs. This is definitely an issue that we need to get fixed to point the main README at the right new locations.

Thank you.
