### ISSUE TITLE
REX-Ray support Raspberry pi ARM arch

### ISSUE THREAD

**Issue by udayansr** [thecodeteam/rexray#1085]
# Summary
REX-Ray does not currently support Raspberry pi on armv71 architecture

# New Feature
REX-Ray should also support the arm architecture. 

# Bug Reports
I tried to install REX-Ray on Raspberry pi on armv71 which has the following details:
Linux raspberrypi2 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux

When I tried to install I got the below message:
pi@raspberrypi2:~ $ curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -
rexray is 64-bit only and not supported on armv7l platforms

**Comment by akutz** [comment]
Hi @udayansr,

The curl bang installation doesn't support it, but you **can** do:

```shell
go get -d github.com/codedellemc/rexray && \
  go generate github.com/codedellemc/rexray && \
  go install github.com/codedellemc/rexray
```

**Comment by clintkitson** [comment]
@udayansr I am really curious about your use case and storage platform that you targeting. Can you describe more about it here?

**Comment by udayansr** [comment]
@akutz tried it but have an error:
pi@raspberrypi2:~ $ go get -d github.com/codedellemc/rexray && go generate github.com/codedellemc/rexray && go install github.com/codedellemc/rexray
# github.com/codedellemc/rexray
go/src/github.com/codedellemc/rexray/rexray.go:118:41: cannot use updateLogLevel(config) (type "github.com/codedellemc/rexray/vendor/github.com/sirupsen/logrus".Level) as type "github.com/thecodeteam/rexray/vendor/github.com/sirupsen/logrus".Level in argument to "github.com/thecodeteam/rexray/libstorage/api/context".SetLogLevel
go/src/github.com/codedellemc/rexray/rexray.go:197:13: cannot use config (type "github.com/codedellemc/rexray/vendor/github.com/akutz/gofig/types".Config) as type "github.com/thecodeteam/rexray/vendor/github.com/akutz/gofig/types".Config in argument to cli.Execute:
	"github.com/codedellemc/rexray/vendor/github.com/akutz/gofig/types".Config does not implement "github.com/thecodeteam/rexray/vendor/github.com/akutz/gofig/types".Config (wrong type for Copy method)
		have Copy() ("github.com/codedellemc/rexray/vendor/github.com/akutz/gofig/types".Config, error)
		want Copy() ("github.com/thecodeteam/rexray/vendor/github.com/akutz/gofig/types".Config, error)


Any help would be great

**Comment by clintkitson** [comment]
Try again but replace codedellemc with thecodeteam in the Go commands.

**Comment by akutz** [comment]
Hi @udayansr,

What @clintkitson said. We were relocating the repo to the new org just as you were doing this. The URLs redirect, but the `go get` command will clone the code to the specified path on the command line, making the build fail. Use this instead:

```shell
go get -d github.com/thecodeteam/rexray && \
  go generate github.com/thecodeteam/rexray && \
  go install github.com/thecodeteam/rexray
```

**Comment by akutz** [comment]
Hi @udayansr,

FWIW, I just verified the above command works using a clean container image. Albeit, my test was x86, but still, I've built it on ARM before.

**Comment by akutz** [comment]
Hi @udayansr (cc @clintkitson),

Here you go:

## Printing the Go version
```shell
$ go version
go version go1.9.1 linux/arm
```

## Printing the Go environment
```shell
$ go env
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/go"
GORACE=""
GOROOT="/home/pi/.go/1.9.1"
GOTOOLDIR="/home/pi/.go/1.9.1/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build159700264=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

## Showing REX-Ray Binary Doesn't Exist
```shell
$ rexray
-bash: rexray: command not found
```

### Use Build Command from Above
```shell
$ go get -d github.com/thecodeteam/rexray && \
>   go generate github.com/thecodeteam/rexray && \
>   go install github.com/thecodeteam/rexray
```

### Running New REX-Ray
```shell
$ rexray version
REX-Ray
-------
Binary: /home/pi/go/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.0+6
OsArch: Linux-ARMv7
Commit: ed07fae9de7c6de49667bf9e008d1b2adec2d453
Formed: Wed, 25 Oct 2017 14:14:42 CDT
```

**Comment by akutz** [comment]
Hi @udayansr (cc @clintkitson),

By the way, I was actually unable to build REX-Ray on my Raspberry Pi due to lack of memory:

```shell
$ go get -d github.com/thecodeteam/rexray && \
>   go generate github.com/thecodeteam/rexray && \
>   go install github.com/thecodeteam/rexray
# github.com/thecodeteam/rexray
/home/pi/.go/1.9.1/pkg/tool/linux_arm/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory
```

I ended up building it on macOS **targeting** ARM:

```shell
$ XGOOS=linux XGOARCH=arm go generate && GOOS=linux GOARCH=arm go build
```

Please note the use of `XGOOS` and `XGOARCH` when I run `go generate`. Those tell `go generate` which OS and Arch to target, but still runs the `go generate` command using the host OS and Arch. The second part of the above command uses the usual `GOOS` and `GOARCH` to target Linux and Arm.

**Comment by udayansr** [comment]
Hi @akutz (cc @clintkitson ),

yup, seems it doesnt build on raspberry pi due to lack of memory. Got the same error:
-------------------------
pi@raspberrypi2:~ $ export PATH=$PATH:/usr/local/go/bin
pi@raspberrypi2:~ $ go get -d github.com/thecodeteam/rexray && go generate github.com/thecodeteam/rexray && go install github.com/thecodeteam/rexray

#github.com/thecodeteam/rexray
/usr/local/go/pkg/tool/linux_arm/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory

pi@raspberrypi2:~ $ 
pi@raspberrypi2:~ $ go version
go version go1.9.1 linux/arm

-------------------------

I dont have a mac, so any other idea's to make it run on raspberry pi 3 model B ? Should i get a higher capacity microSD card ? 

Thanks

**Comment by akutz** [comment]
Hi @udayansr,

It's not related to storage space (your microSD card), but memory. For example, my RPi3 has 8GB RAM but only 5 free:

```shell
$ cat /proc/meminfo
MemTotal:         750632 kB
MemFree:          542300 kB
```

**Comment by akutz** [comment]
Hi @udayansr,

FYI, a Mac isn't required. Just some other Linux-based system that has more memory.

**Comment by akutz** [comment]
Hi @udayansr,

I built REX-Ray `HEAD` for both arm and arm64 and posted them to https://emccode.bintray.com/rexray/unstable/0.11.0+6/. Please note they don't follow the conventional tarball file name. I'm just leaving them there until you can grab them.

**Comment by udayansr** [comment]
Hi @akutz ,

Thanks a ton, it is working now..

pi@raspberrypi2:~/Downloads $ ./rexray.arm version
REX-Ray

Binary: /home/pi/Downloads/rexray.arm
Flavor: client+agent+controller
SemVer: 0.11.0+7
OsArch: Linux-ARMv7
Commit: b60b3f23d083febf86f59a728cd6a86c05a8886f
Formed: Wed, 25 Oct 2017 20:51:14 UTC
pi@raspberrypi2:~/Downloads $ file rexray.arm
rexray.arm: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped


Really appreciate your help. 

Thanks,
Udayan

**Comment by akutz** [comment]
Hi @udayansr (cc @clintkitson),

Just FYI, the curl bang install now works for both ARMv7* and ARMv8* platforms. I just tested it. That's because Travis-CI now builds arm and arm64 versions of the REX-Ray standard binary and deploys them with all `master` builds.

**Comment by udayansr** [comment]
Hi @akutz  (cc @clintkitson )

I tried the curl bang install on RPi3 but still have some issues:

pi@raspberrypi2:~ $ curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
pi@raspberrypi2:~ $ curl -sSL https://dl.bintray.com/emccode/rexray/unstable/0.11.0+8/rexray-Linux-ARMv7-0.11.0+8.tar.gz | sh -sh: 1: Syntax error: "(" unexpected
curl: (23) Failed writing body (240 != 16160)
pi@raspberrypi2:~ $ curl -sSL https://dl.bintray.com/emccode/rexray/unstable/0.11.0+8/ | sh -
sh: 2: Syntax error: newline unexpected

Any help would be great..

**Comment by akutz** [comment]
Hi @udayansr,

Please note that per the [Manual Installation](http://rexray.readthedocs.io/en/latest/user-guide/installation/#install-a-specific-version) docs you need to use the `unstable` release as it points to `master` builds. 

![image](https://user-images.githubusercontent.com/101085/32033693-9edc53ec-b9d3-11e7-8bd9-9737d00c49a8.png)

So, for example:

```shell
$ curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- unstable
```

**Comment by akutz** [comment]
Hi @udayansr,

FYI, you can modify the curl bash line with the flag `-x` after `| sh` to see everything the script is doing:

```shell
$ curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -x -s -- unstable
+ PROG=rexray
+ REPO=rexray
+ BIN_NAME=rexray
+ BINTRAY_URL=https://dl.bintray.com/emccode
+ URL=https://dl.bintray.com/emccode/rexray
+ SCRIPT_URL=https://dl.bintray.com/emccode/rexray/install
+ SCRIPT_CMD=curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s
+ [  = 1 ]
+ CMD=unstable
+ [ unstable = list ]
+ [ unstable = install ]
+ [ unstable = list ]
+ PKG=unstable
+ VERSION=latest
+ FILE_NAME=
+ install
+ uname -m
+ ARCH=armv7l
+ echo armv7l
+ grep -iq armv7
+ ARCH=ARMv7
+ [ latest = latest ]
+ VURL=https://api.bintray.com/packages/emccode/rexray/unstable/versions/_latest
+ curl -sSL https://api.bintray.com/packages/emccode/rexray/unstable/versions/_latest
+ cut -d " -f4
+ VERSION=0.11.0+8
+ uname -s
+ OS=Linux
+ URL=https://dl.bintray.com/emccode/rexray/unstable/0.11.0+8
+ which sudo
+ SUDO=/usr/bin/sudo
+ BIN_DIR=/usr/bin
+ BIN_FILE=/usr/bin/rexray
+ is_coreos
+ + grep DISTRIB_ID /etc/lsb-release
grep CoreOS
+ IS_COREOS=
+ [ -e /etc/redhat-release -o -e /etc/redhat-version ]
+ [ ARMv7 = x86_64 -a -z  ]
+ [ -n  ]
+ [ Linux = Darwin ]
+ [ -z  ]
+ FILE_NAME=rexray-Linux-ARMv7-0.11.0+8.tar.gz
+ URL=https://dl.bintray.com/emccode/rexray/unstable/0.11.0+8/rexray-Linux-ARMv7-0.11.0+8.tar.gz
+ sudo mkdir -p /usr/bin
+ id -u
+ [ 1000 -eq 0 ]
+ /usr/bin/sudo mkdir -p /usr/bin
+ [ 0 -ne 0 ]
+ curl -o rexray-Linux-ARMv7-0.11.0+8.tar.gz -sSL https://dl.bintray.com/emccode/rexray/unstable/0.11.0+8/rexray-Linux-ARMv7-0.11.0+8.tar.gz
```

**Comment by udayansr** [comment]
Thanks @akutz  

It is installed using curl bang install..

**Comment by akutz** [comment]
Hi @udayansr,

Great! May I ask what OS you're using on your Pi? I use the following:

```shell
$ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

Basically I use whatever is the latest RetroPie since my Pi3 is my emulation station :)

**Comment by udayansr** [comment]
Hi @akutz ,

I am currently using the below. thanks again 4 your help :)

pi@raspberrypi2:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
