### ISSUE TITLE
Not working with ebs in Kubernetes

### ISSUE THREAD

**Issue by srflaxu40** [thecodeteam/rexray#1105]
`Nov 07 22:40:06 ip-10-1-1-221 kubelet[3352]: W1107 22:40:06.155112    3352 kuberuntime_container.go:191] Non-root verification doesn't support non-numeric user (root)
Nov 07 22:40:27 ip-10-1-1-221 kubelet[3352]: W1107 22:40:27.907645    3352 conversion.go:110] Could not get instant cpu stats: different number of cpus
Nov 07 22:41:26 ip-10-1-1-221 kubelet[3352]: I1107 22:41:26.831917    3352 reconciler.go:212] operationExecutor.VerifyControllerAttachedVolume started for volume "vol01" (UniqueName: "flexvolume-rexray/flexrex/vol01") pod "pod1" (UID: "81144259-c40c-11e7-b483-0a3c48433232")
Nov 07 22:41:26 ip-10-1-1-221 kubelet[3352]: E1107 22:41:26.833653    3352 nestedpendingoperations.go:264] Operation for "\"flexvolume-rexray/flexrex/vol01\"" failed. No retries permitted until 2017-11-07 22:43:28.833637803 +0000 UTC (durationBeforeRetry 2m2s). Error: Volume not attached according to node status for volume "vol01" (UniqueName: "flexvolume-rexray/flexrex/vol01") pod "pod1" (UID: "81144259-c40c-11e7-b483-0a3c48433232")
Nov 07 22:41:27 ip-10-1-1-221 kubelet[3352]: E1107 22:41:27.258393    3352 kubelet.go:1628] Unable to mount volumes for pod "pod1_default(81144259-c40c-11e7-b483-0a3c48433232)": timeout expired waiting for volumes to attach/mount for pod "default"/"pod1". list of unattached/unmounted volumes=[vol01]; skipping pod
Nov 07 22:41:27 ip-10-1-1-221 kubelet[3352]: E1107 22:41:27.258429    3352 pod_workers.go:182] Error syncing pod 81144259-c40c-11e7-b483-0a3c48433232 ("pod1_default(81144259-c40c-11e7-b483-0a3c48433232)"), skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"pod1". list of unattached/unmounted volumes=[vol01]
Nov 07 22:41:39 ip-10-1-1-221 kubelet[3352]: W1107 22:41:39.378050    3352 plugin-defaults.go:32] flexVolume driver rexray/flexrex: using default GetVolumeName for volume vol01
Nov 07 22:41:39 ip-10-1-1-221 kubelet[3352]: W1107 22:41:39.378083    3352 plugin.go:125] flexVolume driver rexray/flexrex: GetVolumeName is not supported yet. Defaulting to PV or volume name: vol01
`

YAMLS:

`  apiVersion: v1
   kind: PersistentVolume
   metadata:
     name: vol01
   spec:
     capacity:
       storage: 32Gi
     accessModes:
       - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    flexVolume:
      driver: rexray/flexrex
      fsType: xfs
      options:
        volumeID: vol01
        forceAttach: "true"
        forceAttachDelay: "15"
`

`  1 apiVersion: v1
  2 kind: PersistentVolumeClaim
  3 metadata:
  4   name: vol01
  5 spec:
  6   accessModes:
  7     - ReadWriteOnce
  8   resources:
  9     requests:
 10       storage: 10Gi`

`  1 kind: Pod
  2 apiVersion: v1
  3 metadata:
  4   name: pod1
  5 spec:
  6   nodeSelector:
  7     rexray: "true"
  8   containers:
  9   - name: task-pv-container
 10     image: nginx
 11     volumeMounts:
 12     - mountPath: /test
 13       name: vol01
 14   volumes:
 15   - name: vol01
 16     persistentVolumeClaim:
 17       claimName: vol01
`

I set up everything according to [documentation](https://rexray.readthedocs.io/en/stable/user-guide/schedulers/kubernetes/).  Added jq, dropped in the config.yml, installed rexray, checked mount/un-mount, installed flexrex (`rexray install flexrex`) confirmed path was correct and output was correct; restarted kubelet...]

kube version is 1.8+
docker is 17.03.1-ce
rexray is 0.11.0

**Comment by clintkitson** [comment]
Have you made the appropriate flag changes to the kubeadm service? This is what tells the controller to pass all of the actual attaches/detaches to the kubeletes. Otherwise an attach will never get called.

Check `/var/log/flexrex.log` to see whether these calls are actually incoming or not.

**Comment by srflaxu40** [comment]
The log does show successes:

```root@ip-10-1-1-221:~# tail -f /var/log/flexrex.log 
2017-11-07 23:11:00 - success status -  - {"status": "Success"}
2017-11-07 23:12:45 - getvolumename -  - {"forceAttach":"true","forceAttachDelay":"120","kubernetes.io/fsType":"xfs","kubernetes.io/pvOrVolumeName":"vol01","kubernetes.io/readwrite":"rw","volumeID":"vol01"}
2017-11-07 23:12:45 - success status - vol01 - {"status": "Success", "volumeName":"vol-0732b49786f4526be"}```

**Comment by cduchesne** [comment]
working with @srflaxu40 in kubernetes slack - seems error is related to not having `--enable-controller-attach-detach=false` set properly for kubelets

**Comment by srflaxu40** [comment]
Sorry for taking up your guys' time turns out it was my userdata not propagating (needing escaped vars) the vars to the unit file.  Thanks for all your help!
