### ISSUE TITLE
[rexray/rbd docker plugin]docker volume ls show all mirrors in all rbd pools

### ISSUE THREAD

**Issue by mangobowl** [thecodeteam/rexray#1138]
# Summary
In my ceph cluster, there are 2 rbd pools inside, which called "dev" and "prod", and one server uses rexray/rbd docker plugin to connect this ceph cluster. the plugin installation command is as following: `docker plugin install --alias ceph --grant-all-permissions rexray/rbd:0.11.1 RBD_DEFAULTPOOL=dev`

After the plugin installed, I found that `docker volume ls` shows all the mirrors in the "prod" and "dev" pools, instead of "dev" pool only. If there are mirrors with the same name in the "prod" and "dev" pools, this can cause some confusion to docker volumes management.

Since the plugin has been set RBD_DEFAULTPOOL value, can this only show mirrors within RBD_DEFAULTPOOL?

# Environment:
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-87-generic x86_64)
docker 17.06.2-ce
rexray/rbd:0.11.1
ceph-cluster:jewel LTS

**Comment by mangobowl** [comment]
@codenrhoden 
Thank you for your explanation and patience, from which I know more about rexray/rbd and ceph now.

According to your suggestion, adding `RBD_CEPHARGS = "- id admin"` is really a simple solution, and I also verified this in my dev environment, It worked well! Thanks again for your support!

**Comment by codenrhoden** [comment]
@mangobowl Glad it worked! it definitely is not what the argument was intended for, but sometimes we have to get creative. :)
