### ISSUE TITLE
How can i export docker plugin image?

### ISSUE THREAD

**Issue by xiaoxi1989** [thecodeteam/rexray#1159]
# Summary
i have install rexray/rbd,but nowhere to find docker image: rexray/rbd:latest

![image](https://user-images.githubusercontent.com/23303904/35324195-ff16005c-012a-11e8-95bd-b94fa075b6ee.png)

## Version

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.1
OsArch: Linux-x86_64
Commit: 1608180686ac4426b04941b4002fb33b9efd972e
Formed: Wed, 20 Dec 2017 06:26:34 CST
```

**Comment by kacole2** [comment]
@xiaoxi1989 did you install REX-Ray with `docker plugin install rexray/rbd`? If so, those images aren't shown here. You would need to use `docker plugin ls` to view it. 

Also, I see you are using `rexray version`, but I doubt this will work unless you installed REX-Ray as a linux service (not an image).

This is further explained here -> https://rexray.thecodeteam.com/#get-started

**Comment by xiaoxi1989** [comment]
@kacole2 i want to export the docker plugin and move it to the private environment

or another offline installation way?

**Comment by kacole2** [comment]
@xiaoxi1989 Looking at the [Docker docs](https://docs.docker.com/engine/extend/#debugging-plugins) it shows that you can only get information for plugins using `docker plugin ls` and you can debug a container using `docker-runc`. 

I think the best method for you to get an offline installation is to build from source and create your own REX-Ray container using Docker Plugins. The instructions can be found in the [REX-Ray docs](http://rexray.readthedocs.io/en/stable/dev-guide/build-reference/#docker-plug-ins)

**Comment by clintkitson** [comment]
You can do as @kacole2 suggested, from there you should take a look in the `.docker` directory and you will find a directory that is for your plugin. It will include the artifacts, ie. `Dockerfile` generated dynamically that will enable you to just build a vanilla container image before that plugin step.

**Comment by xiaoxi1989** [comment]
@kacole2 @clintkitson  thx,i got it.
