### ISSUE TITLE
add support for the ext3 filesystem as the format for volumes

### ISSUE THREAD

**Issue by cantbewong** [thecodeteam/rexray#278]
ext4 is not universally superior to ext3 in all aspects. There are still use cases where ext3 is desirable to an application because of differences in ordering with regard to fsync on writes/appends and file renames.

**Comment by codenrhoden** [comment]
Issue moved to [codedellemc/libstorage #455](https://github.com/codedellemc/libstorage/issues/455) via [**ZenHub**](https://www.zenhub.com/)

**Comment by codenrhoden** [comment]
fs type is part of the CSI volume capability, so this will come up as part of CSI anyways.
