### ISSUE TITLE
Allow increase of filesystem size

### ISSUE THREAD

**Issue by cduchesne** [thecodeteam/rexray#586]
Related to #585, if we allow increasing of volume size for block devices, we must also enable support for filesystem growth methods (xfs_growfs for xfs and resize2fs for ext4)

**Comment by akutz** [comment]
This answers my confusion I outlined in #585. Thank you. This is a good idea. Thanks for capturing it. Please include a general / parent issue that notes we should allow for mutability / update operations to volumes / other objects in general. Thanks.

**Comment by cduchesne** [comment]
There have been several comments in meetings I've been in. I definitely see the need in applications like Cassandra and MongoDB where knowing the required future size of a volume upon creation is difficult. It is also very wasteful to over-deploy, even if thinly provisioned.

**Comment by codenrhoden** [comment]
leaving this one here for any CLI changes that might be needed.

**Comment by codenrhoden** [comment]
Same comment here as #585
