### ISSUE TITLE
ScaleIO - Support multiple protection domains, automatically 

### ISSUE THREAD

**Issue by cduchesne** [thecodeteam/rexray#590]
REX-Ray only allows easy access to a single protection domain / pool in ScaleIO. In order to allow larger scale deployments, we should have a way of automatically utilizing multiple protections domains with a single service config.

**Comment by rafakei** [comment]
Hi, @cduchesne scaleio sdc is also designed to be able to attach volumes from **multiple scaleio systems.** As you can see a volume id in Linux consists of system id + volume id in SIO, for example:  emc-vol-78b174b134243013-65d0392900000001.  So it'd be great Rexray can specify both system and protection domain for creating volume.

**Comment by codenrhoden** [comment]
Issue moved to [codedellemc/libstorage #463](https://github.com/codedellemc/libstorage/issues/463) via [**ZenHub**](https://www.zenhub.com/)

**Comment by codenrhoden** [comment]
support for multiple pools is already in https://github.com/thecodeteam/csi-scaleio, but not multiple protection domains. Regardless, future ScaleIO enhancements will be made in that driver.
